import { createClient } from "@sanity/client";

// Import Sanity types, generated by Sanity project.
import { buildSrc, ImageSrcInputs } from "@sanity-image/url-builder";
import { createImageUrlBuilder, SanityImageSource } from "@sanity/image-url";

const [_, projectId, dataset, token] = process.env.DATA_PROVIDER!.split(":");
const sanityConfig = {
  projectId,
  dataset,
  useCdn: false,
  apiVersion: "2026-04-07",
  token,
};

export const sanityClient = createClient(sanityConfig);

export const imageUrlBuilder = createImageUrlBuilder(sanityClient);
